name: preview-site-build

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]

jobs:
  tdesign-miniprogram-site:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.number }} > pr-id.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr-id
          path: pr-id.txt
          retention-days: 5

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: pnpm install

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: tdesign-uniapp-site
          path: packages/site/dist
          retention-days: 5
