default.check-filename = true

[default.extend-words]
actived = "actived"
colum = "colum"
loosing = "loosing"
nd = "and"

[files]
extend-exclude = [
  "CHANGELOG*.md", 
  "*.snap",
  "packages/tdesign-app/common/uni.css",
  "packages/tdesign-app/uni_modules/**/*",
  "packages/tdesign/npm/**/*"
]
